
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elastic-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: elastic-service
spec:
  selector:
    app: elastic
  ports:
    - name: elasticsearch
      protocol: TCP
      port: 9200
      targetPort: 9200
    - name: kibana
      protocol: TCP
      port: 5601
      targetPort: 5601

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastic
  template:
    metadata:
      labels:
        app: elastic
    spec:
      volumes:
        - name: elastic-data
          persistentVolumeClaim:
            claimName: elastic-pvc
      containers:
        - name: elasticsearch-kibana
          image: nshou/elasticsearch-kibana:kibana7
          imagePullPolicy: Never
          ports:
            - containerPort: 9200
            - containerPort: 5601
          volumeMounts:
            - name: elastic-data
              mountPath: /elasticsearch-7.17.9/data
              subPath: elasticsearch-data

              